/*
Generated by UnityTwine on 2021-12-25 5:36:59 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class TestStory3: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
	}
    
	// .............
	// #0: By Anonymous

	void passageInit_0()
	{
		this.Passages["By Anonymous"] = new TwinePassage("By Anonymous", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineLink(@"Pokey the Penguin", @"Pokey the Penguin", @"Pokey the Penguin", null, null);	
	}
    
	// .............
	// #1: Pokey the Penguin

	void passageInit_1()
	{
		this.Passages["Pokey the Penguin"] = new TwinePassage("Pokey the Penguin", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineLink(@"THE GAME!", @"THE GAME!", @"THE GAME!", null, null);	
	}
    
	// .............
	// #2: THE GAME!

	void passageInit_2()
	{
		this.Passages["THE GAME!"] = new TwinePassage("THE GAME!", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineLink(@"By Anonymous", @"By Anonymous", @"By Anonymous", null, null);	
	}
    
	// .............
	// #3: Storytelling

	void passageInit_3()
	{
		this.Passages["Storytelling"] = new TwinePassage("Storytelling", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"<style role=""stylesheet"" id=""twine-user-stylesheet"" type=""text/twine-css""></style><script role=""script"" id=""twine-user-script"" type=""text/twine-javascript""></script><tw-passagedata pid=""1"" name=""The Center"" tags="""" position=""1759,949"" size=""100,100"">");yield return new TwineLink(@"A", @"A", @"A", null, null);
		yield return new TwineLink(@"B", @"B", @"B", null, null);
		yield return new TwineLink(@"C", @"C", @"C", null, null);
		yield return new TwineText(@"</tw-passagedata><tw-passagedata pid=""2"" name=""A"" tags="""" position=""1554,1149"" size=""100,100"">");yield return new TwineLink(@"The Center", @"The Center", @"The Center", null, null); 
		yield return new TwineLink(@"B", @"B", @"B", null, null);
		yield return new TwineLink(@"C", @"C", @"C", null, null);yield return new TwineText(@"</tw-passagedata><tw-passagedata pid=""3"" name=""B"" tags="""" position=""1954,1150"" size=""100,100"">");yield return new TwineLink(@"The Center", @"The Center", @"The Center", null, null); 
		yield return new TwineLink(@"A", @"A", @"A", null, null);
		yield return new TwineLink(@"C", @"C", @"C", null, null);yield return new TwineText(@"</tw-passagedata><tw-passagedata pid=""4"" name=""C"" tags="""" position=""1756,743"" size=""100,100"">");yield return new TwineLink(@"The Center", @"The Center", @"The Center", null, null); 
		yield return new TwineLink(@"A", @"A", @"A", null, null);
		yield return new TwineLink(@"B", @"B", @"B", null, null);yield return new TwineText(@" </tw-passagedata></tw-storydata>");	
	}

}