/*
Generated by UnityTwine on 2022-02-16 8:32:37 PM
https://github.com/daterre/UnityTwine
*/
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityTwine;

public class Wordplay: TwineStory
{
	public override TwineVar this[string name]
	{
		get
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
		set
		{
			switch(name)
			{
				default: throw new KeyNotFoundException(string.Format("There is no variable with the name '{0}'.", name));
			}
		}
	}


	void Awake() {
		base.Init();
		passageInit_0();
		passageInit_1();
		passageInit_2();
		passageInit_3();
		passageInit_4();
		passageInit_5();
		passageInit_6();
	}
    
	// .............
	// #0: Credits

	void passageInit_0()
	{
		this.Passages["Credits"] = new TwinePassage("Credits", new string[]{  }, passageExecute_0);
	}

	IEnumerable<TwineOutput> passageExecute_0()
	{
		yield return new TwineText(@"created by Timothy Winston Walker Case");	
	}
    
	// .............
	// #1: StoryMenu

	void passageInit_1()
	{
		this.Passages["StoryMenu"] = new TwinePassage("StoryMenu", new string[]{  }, passageExecute_1);
	}

	IEnumerable<TwineOutput> passageExecute_1()
	{
		yield return new TwineLink(@"Start", @"Start", @"Start", null, null);
		yield return new TwineLink(@"Credits", @"Credits", @"Credits", null, null);	
	}
    
	// .............
	// #2: Start

	void passageInit_2()
	{
		this.Passages["Start"] = new TwinePassage("Start", new string[]{  }, passageExecute_2);
	}

	IEnumerable<TwineOutput> passageExecute_2()
	{
		yield return new TwineText(@"Welcome to Wordplay!");
		yield return new TwineLink(@"NEW GAME", @"NEW GAME", @"StoryAuthor", null, null);
		yield return new TwineLink(@"MAIN MENU", @"MAIN MENU", @"StoryMenu", null, null);	
	}
    
	// .............
	// #3: StoryInit

	void passageInit_3()
	{
		this.Passages["StoryInit"] = new TwinePassage("StoryInit", new string[]{  }, passageExecute_3);
	}

	IEnumerable<TwineOutput> passageExecute_3()
	{
		yield return new TwineText(@"/% Place your story's setup code in this passage.");
		yield return new TwineText(@"Any macros in this passage will be run before the Start passage (or any passage you wish to Test Play) is run. %/");	
	}
    
	// .............
	// #4: Wordplay

	void passageInit_4()
	{
		this.Passages["Wordplay"] = new TwinePassage("Wordplay", new string[]{  }, passageExecute_4);
	}

	IEnumerable<TwineOutput> passageExecute_4()
	{
		yield return new TwineLink(@"BEGIN!", @"BEGIN!", @"1", null, null);	
	}
    
	// .............
	// #5: StoryAuthor

	void passageInit_5()
	{
		this.Passages["StoryAuthor"] = new TwinePassage("StoryAuthor", new string[]{  }, passageExecute_5);
	}

	IEnumerable<TwineOutput> passageExecute_5()
	{
		yield return new TwineLink(@"by Tim Case", @"by Tim Case", @"Wordplay", null, null);	
	}
    
	// .............
	// #6: 1

	void passageInit_6()
	{
		this.Passages["1"] = new TwinePassage("1", new string[]{  }, passageExecute_6);
	}

	IEnumerable<TwineOutput> passageExecute_6()
	{
		yield return new TwineLink(@"Back", @"Back", @"Wordplay", null, null);
		yield return new TwineLink(@"MAIN MENU", @"MAIN MENU", @"StoryMenu", null, null);	
	}

}